[package]
distribution = "2201.13.1"
org = "ballerina"
name = "pdf"
version = "0.9.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pdf", "html", "html-to-pdf", "converter", "document"]
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerina-pdf"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "pdf-native"
version = "0.9.0"
path = "../native/build/libs/pdf-native-0.9.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "3.0.4"
path = "./lib/pdfbox-3.0.4.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox-io"
version = "3.0.4"
path = "./lib/pdfbox-io-3.0.4.jar"

[[platform.java21.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "3.0.4"
path = "./lib/fontbox-3.0.4.jar"

[[platform.java21.dependency]]
groupId = "commons-logging"
artifactId = "commons-logging"
version = "1.3.4"
path = "./lib/commons-logging-1.3.4.jar"

[[platform.java21.dependency]]
groupId = "org.jsoup"
artifactId = "jsoup"
version = "1.18.3"
path = "./lib/jsoup-1.18.3.jar"

[[platform.java21.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-jdk14"
version = "2.0.16"
path = "./lib/slf4j-jdk14-2.0.16.jar"

[[platform.java21.dependency]]
groupId = "org.htmlunit"
artifactId = "htmlunit-cssparser"
version = "4.5.0"
path = "./lib/htmlunit-cssparser-4.5.0.jar"
